name = "log187-hub"
pages_build_output_dir = "public"
compatibility_date = "2023-10-30"

# Laisser Cloudflare gérer le routage des fonctions basé sur les fichiers
# main = "functions/api/[[path]].js" 

[[d1_databases]]
binding = "DB"
database_name = "log187-missions"
database_id = "9d5ea2cb-06b6-4633-ad26-cd0225f56d06"
